with-expecter: true

inpackage: false

dir: "mocks/{{.PackageName}}"

packages:

  github.com/fullstackdev42/mp-emailer/internal/database:
    interfaces:
      Migrator:

  github.com/fullstackdev42/mp-emailer/email:
    interfaces:
      SMTPClient:
      MailgunClient:

  github.com/fullstackdev42/mp-emailer/server:
    interfaces:
      TemplateRenderer:
