with-expecter: true

inpackage: true

dir: "mocks/{{.PackageName}}"

packages:

  github.com/fullstackdev42/mp-emailer/internal/database:
    interfaces:
      Migrator:

  github.com/fullstackdev42/mp-emailer/user:
    interfaces:
      ServiceInterface:
      Repository:

  github.com/fullstackdev42/mp-emailer/campaign:
    interfaces:
      ServiceInterface:
      RepresentativeLookupServiceInterface:
      ClientInterface:
      RepositoryInterface:

  github.com/fullstackdev42/mp-emailer/email:
    interfaces:
      SMTPClient:
      MailgunClient:
