dir: "mocks/{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
inpackage: false
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
with-expecter: true

packages:

  github.com/jonesrussell/mp-emailer/campaign:
    interfaces:
      ServiceInterface:
      RepresentativeLookupServiceInterface:
      ClientInterface:
      RepositoryInterface:

  github.com/jonesrussell/mp-emailer/email:
    interfaces:
      ServiceInterface:
      Service:
      SMTPClient:
      MailgunClient:

  github.com/jonesrussell/mp-emailer/shared:
    interfaces:
      ErrorHandlerInterface:
      TemplateRendererInterface:
      FlashHandlerInterface:

  github.com/jonesrussell/mp-emailer/user:
    interfaces:
      RepositoryInterface:
      ServiceInterface:
      SessionManager:

  github.com/jonesrussell/mp-emailer/middleware:
    interfaces:
      SessionManager:
      SessionStore:

  github.com/jonesrussell/mp-emailer/database:
    interfaces:
      Database:
