dir: "mocks/{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
inpackage: false
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
with-expecter: true

packages:

  github.com/fullstackdev42/mp-emailer/campaign:
    interfaces:
      ServiceInterface:
      RepresentativeLookupServiceInterface:
      ClientInterface:
      RepositoryInterface:

  github.com/fullstackdev42/mp-emailer/database/core:
    interfaces:
      Interface:
      Result:
      AssociationInterface:
      Migrator:

  github.com/fullstackdev42/mp-emailer/database/factories:
    interfaces:
      Factory:

  github.com/fullstackdev42/mp-emailer/database/seeders:
    interfaces:
      Seeder:

  github.com/fullstackdev42/mp-emailer/email:
    interfaces:
      Service:
      SMTPClient:
      MailgunClient:

  github.com/fullstackdev42/mp-emailer/shared:
    interfaces:
      ErrorHandlerInterface:
      TemplateRendererInterface:
      FlashHandlerInterface:

  github.com/fullstackdev42/mp-emailer/user:
    interfaces:
      RepositoryInterface:
      ServiceInterface:
      SessionManager:

  github.com/fullstackdev42/mp-emailer/middleware:
    interfaces:
      SessionManager:
      SessionStore:
