app:
  debug: false
  env: development
  host: 0.0.0.0
  port: 8080

database:
  port: 3306

email:
  provider: smtp
  smtp:
    port: 587

log:
  file: storage/logs/app.log
  level: info

server:
  migrations_path: database/migrations 