with-expecter: true
inpackage: false
filename: "mock_{{.InterfaceName}}.go"
dir: "../mocks/campaign"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"

packages:
  github.com/fullstackdev42/mp-emailer/campaign:
    interfaces:
      ServiceInterface:
      RepresentativeLookupServiceInterface:
      ClientInterface:
      RepositoryInterface:
