// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSeeder is an autogenerated mock type for the Seeder type
type MockSeeder struct {
	mock.Mock
}

type MockSeeder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSeeder) EXPECT() *MockSeeder_Expecter {
	return &MockSeeder_Expecter{mock: &_m.Mock}
}

// Seed provides a mock function with given fields:
func (_m *MockSeeder) Seed() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Seed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSeeder_Seed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Seed'
type MockSeeder_Seed_Call struct {
	*mock.Call
}

// Seed is a helper method to define mock.On call
func (_e *MockSeeder_Expecter) Seed() *MockSeeder_Seed_Call {
	return &MockSeeder_Seed_Call{Call: _e.mock.On("Seed")}
}

func (_c *MockSeeder_Seed_Call) Run(run func()) *MockSeeder_Seed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSeeder_Seed_Call) Return(_a0 error) *MockSeeder_Seed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSeeder_Seed_Call) RunAndReturn(run func() error) *MockSeeder_Seed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSeeder creates a new instance of MockSeeder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSeeder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSeeder {
	mock := &MockSeeder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
