// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"

	sessions "github.com/gorilla/sessions"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// ClearSession provides a mock function with given fields: c, name
func (_m *MockManager) ClearSession(c echo.Context, name string) error {
	ret := _m.Called(c, name)

	if len(ret) == 0 {
		panic("no return value specified for ClearSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) error); ok {
		r0 = rf(c, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_ClearSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSession'
type MockManager_ClearSession_Call struct {
	*mock.Call
}

// ClearSession is a helper method to define mock.On call
//   - c echo.Context
//   - name string
func (_e *MockManager_Expecter) ClearSession(c interface{}, name interface{}) *MockManager_ClearSession_Call {
	return &MockManager_ClearSession_Call{Call: _e.mock.On("ClearSession", c, name)}
}

func (_c *MockManager_ClearSession_Call) Run(run func(c echo.Context, name string)) *MockManager_ClearSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(string))
	})
	return _c
}

func (_c *MockManager_ClearSession_Call) Return(_a0 error) *MockManager_ClearSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_ClearSession_Call) RunAndReturn(run func(echo.Context, string) error) *MockManager_ClearSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSessionValue provides a mock function with given fields: sess, key
func (_m *MockManager) DeleteSessionValue(sess *sessions.Session, key string) {
	_m.Called(sess, key)
}

// MockManager_DeleteSessionValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSessionValue'
type MockManager_DeleteSessionValue_Call struct {
	*mock.Call
}

// DeleteSessionValue is a helper method to define mock.On call
//   - sess *sessions.Session
//   - key string
func (_e *MockManager_Expecter) DeleteSessionValue(sess interface{}, key interface{}) *MockManager_DeleteSessionValue_Call {
	return &MockManager_DeleteSessionValue_Call{Call: _e.mock.On("DeleteSessionValue", sess, key)}
}

func (_c *MockManager_DeleteSessionValue_Call) Run(run func(sess *sessions.Session, key string)) *MockManager_DeleteSessionValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sessions.Session), args[1].(string))
	})
	return _c
}

func (_c *MockManager_DeleteSessionValue_Call) Return() *MockManager_DeleteSessionValue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_DeleteSessionValue_Call) RunAndReturn(run func(*sessions.Session, string)) *MockManager_DeleteSessionValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: c, name
func (_m *MockManager) GetSession(c echo.Context, name string) (*sessions.Session, error) {
	ret := _m.Called(c, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *sessions.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) (*sessions.Session, error)); ok {
		return rf(c, name)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, string) *sessions.Session); ok {
		r0 = rf(c, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, string) error); ok {
		r1 = rf(c, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockManager_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - c echo.Context
//   - name string
func (_e *MockManager_Expecter) GetSession(c interface{}, name interface{}) *MockManager_GetSession_Call {
	return &MockManager_GetSession_Call{Call: _e.mock.On("GetSession", c, name)}
}

func (_c *MockManager_GetSession_Call) Run(run func(c echo.Context, name string)) *MockManager_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(string))
	})
	return _c
}

func (_c *MockManager_GetSession_Call) Return(_a0 *sessions.Session, _a1 error) *MockManager_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetSession_Call) RunAndReturn(run func(echo.Context, string) (*sessions.Session, error)) *MockManager_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionValue provides a mock function with given fields: sess, key
func (_m *MockManager) GetSessionValue(sess *sessions.Session, key string) interface{} {
	ret := _m.Called(sess, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionValue")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(*sessions.Session, string) interface{}); ok {
		r0 = rf(sess, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// MockManager_GetSessionValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionValue'
type MockManager_GetSessionValue_Call struct {
	*mock.Call
}

// GetSessionValue is a helper method to define mock.On call
//   - sess *sessions.Session
//   - key string
func (_e *MockManager_Expecter) GetSessionValue(sess interface{}, key interface{}) *MockManager_GetSessionValue_Call {
	return &MockManager_GetSessionValue_Call{Call: _e.mock.On("GetSessionValue", sess, key)}
}

func (_c *MockManager_GetSessionValue_Call) Run(run func(sess *sessions.Session, key string)) *MockManager_GetSessionValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sessions.Session), args[1].(string))
	})
	return _c
}

func (_c *MockManager_GetSessionValue_Call) Return(_a0 interface{}) *MockManager_GetSessionValue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_GetSessionValue_Call) RunAndReturn(run func(*sessions.Session, string) interface{}) *MockManager_GetSessionValue_Call {
	_c.Call.Return(run)
	return _c
}

// IsAuthenticated provides a mock function with given fields: c
func (_m *MockManager) IsAuthenticated(c echo.Context) bool {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for IsAuthenticated")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(echo.Context) bool); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockManager_IsAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAuthenticated'
type MockManager_IsAuthenticated_Call struct {
	*mock.Call
}

// IsAuthenticated is a helper method to define mock.On call
//   - c echo.Context
func (_e *MockManager_Expecter) IsAuthenticated(c interface{}) *MockManager_IsAuthenticated_Call {
	return &MockManager_IsAuthenticated_Call{Call: _e.mock.On("IsAuthenticated", c)}
}

func (_c *MockManager_IsAuthenticated_Call) Run(run func(c echo.Context)) *MockManager_IsAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *MockManager_IsAuthenticated_Call) Return(_a0 bool) *MockManager_IsAuthenticated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_IsAuthenticated_Call) RunAndReturn(run func(echo.Context) bool) *MockManager_IsAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateSession provides a mock function with given fields: c, name
func (_m *MockManager) RegenerateSession(c echo.Context, name string) (*sessions.Session, error) {
	ret := _m.Called(c, name)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateSession")
	}

	var r0 *sessions.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) (*sessions.Session, error)); ok {
		return rf(c, name)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, string) *sessions.Session); ok {
		r0 = rf(c, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, string) error); ok {
		r1 = rf(c, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_RegenerateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateSession'
type MockManager_RegenerateSession_Call struct {
	*mock.Call
}

// RegenerateSession is a helper method to define mock.On call
//   - c echo.Context
//   - name string
func (_e *MockManager_Expecter) RegenerateSession(c interface{}, name interface{}) *MockManager_RegenerateSession_Call {
	return &MockManager_RegenerateSession_Call{Call: _e.mock.On("RegenerateSession", c, name)}
}

func (_c *MockManager_RegenerateSession_Call) Run(run func(c echo.Context, name string)) *MockManager_RegenerateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(string))
	})
	return _c
}

func (_c *MockManager_RegenerateSession_Call) Return(_a0 *sessions.Session, _a1 error) *MockManager_RegenerateSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_RegenerateSession_Call) RunAndReturn(run func(echo.Context, string) (*sessions.Session, error)) *MockManager_RegenerateSession_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function with given fields: c, _a1
func (_m *MockManager) SaveSession(c echo.Context, _a1 *sessions.Session) error {
	ret := _m.Called(c, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, *sessions.Session) error); ok {
		r0 = rf(c, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type MockManager_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - c echo.Context
//   - _a1 *sessions.Session
func (_e *MockManager_Expecter) SaveSession(c interface{}, _a1 interface{}) *MockManager_SaveSession_Call {
	return &MockManager_SaveSession_Call{Call: _e.mock.On("SaveSession", c, _a1)}
}

func (_c *MockManager_SaveSession_Call) Run(run func(c echo.Context, _a1 *sessions.Session)) *MockManager_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(*sessions.Session))
	})
	return _c
}

func (_c *MockManager_SaveSession_Call) Return(_a0 error) *MockManager_SaveSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_SaveSession_Call) RunAndReturn(run func(echo.Context, *sessions.Session) error) *MockManager_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}

// SetAuthenticated provides a mock function with given fields: c, authenticated
func (_m *MockManager) SetAuthenticated(c echo.Context, authenticated bool) error {
	ret := _m.Called(c, authenticated)

	if len(ret) == 0 {
		panic("no return value specified for SetAuthenticated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, bool) error); ok {
		r0 = rf(c, authenticated)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_SetAuthenticated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAuthenticated'
type MockManager_SetAuthenticated_Call struct {
	*mock.Call
}

// SetAuthenticated is a helper method to define mock.On call
//   - c echo.Context
//   - authenticated bool
func (_e *MockManager_Expecter) SetAuthenticated(c interface{}, authenticated interface{}) *MockManager_SetAuthenticated_Call {
	return &MockManager_SetAuthenticated_Call{Call: _e.mock.On("SetAuthenticated", c, authenticated)}
}

func (_c *MockManager_SetAuthenticated_Call) Run(run func(c echo.Context, authenticated bool)) *MockManager_SetAuthenticated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(bool))
	})
	return _c
}

func (_c *MockManager_SetAuthenticated_Call) Return(_a0 error) *MockManager_SetAuthenticated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_SetAuthenticated_Call) RunAndReturn(run func(echo.Context, bool) error) *MockManager_SetAuthenticated_Call {
	_c.Call.Return(run)
	return _c
}

// SetSessionValues provides a mock function with given fields: sess, userData
func (_m *MockManager) SetSessionValues(sess *sessions.Session, userData interface{}) {
	_m.Called(sess, userData)
}

// MockManager_SetSessionValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSessionValues'
type MockManager_SetSessionValues_Call struct {
	*mock.Call
}

// SetSessionValues is a helper method to define mock.On call
//   - sess *sessions.Session
//   - userData interface{}
func (_e *MockManager_Expecter) SetSessionValues(sess interface{}, userData interface{}) *MockManager_SetSessionValues_Call {
	return &MockManager_SetSessionValues_Call{Call: _e.mock.On("SetSessionValues", sess, userData)}
}

func (_c *MockManager_SetSessionValues_Call) Run(run func(sess *sessions.Session, userData interface{})) *MockManager_SetSessionValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sessions.Session), args[1].(interface{}))
	})
	return _c
}

func (_c *MockManager_SetSessionValues_Call) Return() *MockManager_SetSessionValues_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_SetSessionValues_Call) RunAndReturn(run func(*sessions.Session, interface{})) *MockManager_SetSessionValues_Call {
	_c.Call.Return(run)
	return _c
}

// StartCleanup provides a mock function with given fields: ctx
func (_m *MockManager) StartCleanup(ctx context.Context) {
	_m.Called(ctx)
}

// MockManager_StartCleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartCleanup'
type MockManager_StartCleanup_Call struct {
	*mock.Call
}

// StartCleanup is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockManager_Expecter) StartCleanup(ctx interface{}) *MockManager_StartCleanup_Call {
	return &MockManager_StartCleanup_Call{Call: _e.mock.On("StartCleanup", ctx)}
}

func (_c *MockManager_StartCleanup_Call) Run(run func(ctx context.Context)) *MockManager_StartCleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockManager_StartCleanup_Call) Return() *MockManager_StartCleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_StartCleanup_Call) RunAndReturn(run func(context.Context)) *MockManager_StartCleanup_Call {
	_c.Call.Return(run)
	return _c
}

// StopCleanup provides a mock function with given fields:
func (_m *MockManager) StopCleanup() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopCleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_StopCleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopCleanup'
type MockManager_StopCleanup_Call struct {
	*mock.Call
}

// StopCleanup is a helper method to define mock.On call
func (_e *MockManager_Expecter) StopCleanup() *MockManager_StopCleanup_Call {
	return &MockManager_StopCleanup_Call{Call: _e.mock.On("StopCleanup")}
}

func (_c *MockManager_StopCleanup_Call) Run(run func()) *MockManager_StopCleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockManager_StopCleanup_Call) Return(_a0 error) *MockManager_StopCleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_StopCleanup_Call) RunAndReturn(run func() error) *MockManager_StopCleanup_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateSession provides a mock function with given fields: name
func (_m *MockManager) ValidateSession(name string) echo.MiddlewareFunc {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSession")
	}

	var r0 echo.MiddlewareFunc
	if rf, ok := ret.Get(0).(func(string) echo.MiddlewareFunc); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.MiddlewareFunc)
		}
	}

	return r0
}

// MockManager_ValidateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSession'
type MockManager_ValidateSession_Call struct {
	*mock.Call
}

// ValidateSession is a helper method to define mock.On call
//   - name string
func (_e *MockManager_Expecter) ValidateSession(name interface{}) *MockManager_ValidateSession_Call {
	return &MockManager_ValidateSession_Call{Call: _e.mock.On("ValidateSession", name)}
}

func (_c *MockManager_ValidateSession_Call) Run(run func(name string)) *MockManager_ValidateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_ValidateSession_Call) Return(_a0 echo.MiddlewareFunc) *MockManager_ValidateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_ValidateSession_Call) RunAndReturn(run func(string) echo.MiddlewareFunc) *MockManager_ValidateSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
