// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"

	sessions "github.com/gorilla/sessions"
)

// MockManager is an autogenerated mock type for the Manager type
type MockManager struct {
	mock.Mock
}

type MockManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManager) EXPECT() *MockManager_Expecter {
	return &MockManager_Expecter{mock: &_m.Mock}
}

// ClearSession provides a mock function with given fields: c, name
func (_m *MockManager) ClearSession(c echo.Context, name string) error {
	ret := _m.Called(c, name)

	if len(ret) == 0 {
		panic("no return value specified for ClearSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) error); ok {
		r0 = rf(c, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_ClearSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSession'
type MockManager_ClearSession_Call struct {
	*mock.Call
}

// ClearSession is a helper method to define mock.On call
//   - c echo.Context
//   - name string
func (_e *MockManager_Expecter) ClearSession(c interface{}, name interface{}) *MockManager_ClearSession_Call {
	return &MockManager_ClearSession_Call{Call: _e.mock.On("ClearSession", c, name)}
}

func (_c *MockManager_ClearSession_Call) Run(run func(c echo.Context, name string)) *MockManager_ClearSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(string))
	})
	return _c
}

func (_c *MockManager_ClearSession_Call) Return(_a0 error) *MockManager_ClearSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_ClearSession_Call) RunAndReturn(run func(echo.Context, string) error) *MockManager_ClearSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: c, name
func (_m *MockManager) GetSession(c echo.Context, name string) (*sessions.Session, error) {
	ret := _m.Called(c, name)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *sessions.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(echo.Context, string) (*sessions.Session, error)); ok {
		return rf(c, name)
	}
	if rf, ok := ret.Get(0).(func(echo.Context, string) *sessions.Session); ok {
		r0 = rf(c, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sessions.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(echo.Context, string) error); ok {
		r1 = rf(c, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockManager_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockManager_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - c echo.Context
//   - name string
func (_e *MockManager_Expecter) GetSession(c interface{}, name interface{}) *MockManager_GetSession_Call {
	return &MockManager_GetSession_Call{Call: _e.mock.On("GetSession", c, name)}
}

func (_c *MockManager_GetSession_Call) Run(run func(c echo.Context, name string)) *MockManager_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(string))
	})
	return _c
}

func (_c *MockManager_GetSession_Call) Return(_a0 *sessions.Session, _a1 error) *MockManager_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockManager_GetSession_Call) RunAndReturn(run func(echo.Context, string) (*sessions.Session, error)) *MockManager_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function with given fields: c, _a1
func (_m *MockManager) SaveSession(c echo.Context, _a1 *sessions.Session) error {
	ret := _m.Called(c, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, *sessions.Session) error); ok {
		r0 = rf(c, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockManager_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type MockManager_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - c echo.Context
//   - _a1 *sessions.Session
func (_e *MockManager_Expecter) SaveSession(c interface{}, _a1 interface{}) *MockManager_SaveSession_Call {
	return &MockManager_SaveSession_Call{Call: _e.mock.On("SaveSession", c, _a1)}
}

func (_c *MockManager_SaveSession_Call) Run(run func(c echo.Context, _a1 *sessions.Session)) *MockManager_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(*sessions.Session))
	})
	return _c
}

func (_c *MockManager_SaveSession_Call) Return(_a0 error) *MockManager_SaveSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_SaveSession_Call) RunAndReturn(run func(echo.Context, *sessions.Session) error) *MockManager_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}

// SetSessionValues provides a mock function with given fields: sess, userData
func (_m *MockManager) SetSessionValues(sess *sessions.Session, userData interface{}) {
	_m.Called(sess, userData)
}

// MockManager_SetSessionValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSessionValues'
type MockManager_SetSessionValues_Call struct {
	*mock.Call
}

// SetSessionValues is a helper method to define mock.On call
//   - sess *sessions.Session
//   - userData interface{}
func (_e *MockManager_Expecter) SetSessionValues(sess interface{}, userData interface{}) *MockManager_SetSessionValues_Call {
	return &MockManager_SetSessionValues_Call{Call: _e.mock.On("SetSessionValues", sess, userData)}
}

func (_c *MockManager_SetSessionValues_Call) Run(run func(sess *sessions.Session, userData interface{})) *MockManager_SetSessionValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*sessions.Session), args[1].(interface{}))
	})
	return _c
}

func (_c *MockManager_SetSessionValues_Call) Return() *MockManager_SetSessionValues_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockManager_SetSessionValues_Call) RunAndReturn(run func(*sessions.Session, interface{})) *MockManager_SetSessionValues_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateSession provides a mock function with given fields: name
func (_m *MockManager) ValidateSession(name string) echo.MiddlewareFunc {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ValidateSession")
	}

	var r0 echo.MiddlewareFunc
	if rf, ok := ret.Get(0).(func(string) echo.MiddlewareFunc); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.MiddlewareFunc)
		}
	}

	return r0
}

// MockManager_ValidateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateSession'
type MockManager_ValidateSession_Call struct {
	*mock.Call
}

// ValidateSession is a helper method to define mock.On call
//   - name string
func (_e *MockManager_Expecter) ValidateSession(name interface{}) *MockManager_ValidateSession_Call {
	return &MockManager_ValidateSession_Call{Call: _e.mock.On("ValidateSession", name)}
}

func (_c *MockManager_ValidateSession_Call) Run(run func(name string)) *MockManager_ValidateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockManager_ValidateSession_Call) Return(_a0 echo.MiddlewareFunc) *MockManager_ValidateSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockManager_ValidateSession_Call) RunAndReturn(run func(string) echo.MiddlewareFunc) *MockManager_ValidateSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockManager creates a new instance of MockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManager {
	mock := &MockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
