// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockMigrator is an autogenerated mock type for the Migrator type
type MockMigrator struct {
	mock.Mock
}

type MockMigrator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrator) EXPECT() *MockMigrator_Expecter {
	return &MockMigrator_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockMigrator) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMigrator_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMigrator_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMigrator_Expecter) Close() *MockMigrator_Close_Call {
	return &MockMigrator_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMigrator_Close_Call) Run(run func()) *MockMigrator_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMigrator_Close_Call) Return(_a0 error) *MockMigrator_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMigrator_Close_Call) RunAndReturn(run func() error) *MockMigrator_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function with given fields:
func (_m *MockMigrator) Up() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMigrator_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockMigrator_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
func (_e *MockMigrator_Expecter) Up() *MockMigrator_Up_Call {
	return &MockMigrator_Up_Call{Call: _e.mock.On("Up")}
}

func (_c *MockMigrator_Up_Call) Run(run func()) *MockMigrator_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMigrator_Up_Call) Return(_a0 error) *MockMigrator_Up_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMigrator_Up_Call) RunAndReturn(run func() error) *MockMigrator_Up_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMigrator creates a new instance of MockMigrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrator {
	mock := &MockMigrator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
