// Code generated by mockery v2.46.3. DO NOT EDIT.

package campaign

import mock "github.com/stretchr/testify/mock"

// MockRepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type MockRepositoryInterface struct {
	mock.Mock
}

type MockRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepositoryInterface) EXPECT() *MockRepositoryInterface_Expecter {
	return &MockRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: campaign
func (_m *MockRepositoryInterface) Create(campaign *Campaign) error {
	ret := _m.Called(campaign)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Campaign) error); ok {
		r0 = rf(campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - campaign *Campaign
func (_e *MockRepositoryInterface_Expecter) Create(campaign interface{}) *MockRepositoryInterface_Create_Call {
	return &MockRepositoryInterface_Create_Call{Call: _e.mock.On("Create", campaign)}
}

func (_c *MockRepositoryInterface_Create_Call) Run(run func(campaign *Campaign)) *MockRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Campaign))
	})
	return _c
}

func (_c *MockRepositoryInterface_Create_Call) Return(_a0 error) *MockRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryInterface_Create_Call) RunAndReturn(run func(*Campaign) error) *MockRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *MockRepositoryInterface) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockRepositoryInterface_Expecter) Delete(id interface{}) *MockRepositoryInterface_Delete_Call {
	return &MockRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockRepositoryInterface_Delete_Call) Run(run func(id int)) *MockRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepositoryInterface_Delete_Call) Return(_a0 error) *MockRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryInterface_Delete_Call) RunAndReturn(run func(int) error) *MockRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *MockRepositoryInterface) GetAll() ([]Campaign, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]Campaign, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []Campaign); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryInterface_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepositoryInterface_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockRepositoryInterface_Expecter) GetAll() *MockRepositoryInterface_GetAll_Call {
	return &MockRepositoryInterface_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockRepositoryInterface_GetAll_Call) Run(run func()) *MockRepositoryInterface_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepositoryInterface_GetAll_Call) Return(_a0 []Campaign, _a1 error) *MockRepositoryInterface_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryInterface_GetAll_Call) RunAndReturn(run func() ([]Campaign, error)) *MockRepositoryInterface_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *MockRepositoryInterface) GetByID(id int) (*Campaign, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*Campaign, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *Campaign); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryInterface_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepositoryInterface_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *MockRepositoryInterface_Expecter) GetByID(id interface{}) *MockRepositoryInterface_GetByID_Call {
	return &MockRepositoryInterface_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockRepositoryInterface_GetByID_Call) Run(run func(id int)) *MockRepositoryInterface_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepositoryInterface_GetByID_Call) Return(_a0 *Campaign, _a1 error) *MockRepositoryInterface_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryInterface_GetByID_Call) RunAndReturn(run func(int) (*Campaign, error)) *MockRepositoryInterface_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCampaign provides a mock function with given fields: id
func (_m *MockRepositoryInterface) GetCampaign(id int) (*Campaign, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetCampaign")
	}

	var r0 *Campaign
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*Campaign, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) *Campaign); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Campaign)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepositoryInterface_GetCampaign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCampaign'
type MockRepositoryInterface_GetCampaign_Call struct {
	*mock.Call
}

// GetCampaign is a helper method to define mock.On call
//   - id int
func (_e *MockRepositoryInterface_Expecter) GetCampaign(id interface{}) *MockRepositoryInterface_GetCampaign_Call {
	return &MockRepositoryInterface_GetCampaign_Call{Call: _e.mock.On("GetCampaign", id)}
}

func (_c *MockRepositoryInterface_GetCampaign_Call) Run(run func(id int)) *MockRepositoryInterface_GetCampaign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRepositoryInterface_GetCampaign_Call) Return(_a0 *Campaign, _a1 error) *MockRepositoryInterface_GetCampaign_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepositoryInterface_GetCampaign_Call) RunAndReturn(run func(int) (*Campaign, error)) *MockRepositoryInterface_GetCampaign_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: campaign
func (_m *MockRepositoryInterface) Update(campaign *Campaign) error {
	ret := _m.Called(campaign)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Campaign) error); ok {
		r0 = rf(campaign)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - campaign *Campaign
func (_e *MockRepositoryInterface_Expecter) Update(campaign interface{}) *MockRepositoryInterface_Update_Call {
	return &MockRepositoryInterface_Update_Call{Call: _e.mock.On("Update", campaign)}
}

func (_c *MockRepositoryInterface_Update_Call) Run(run func(campaign *Campaign)) *MockRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Campaign))
	})
	return _c
}

func (_c *MockRepositoryInterface_Update_Call) Return(_a0 error) *MockRepositoryInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepositoryInterface_Update_Call) RunAndReturn(run func(*Campaign) error) *MockRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepositoryInterface creates a new instance of MockRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
