// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	logger "github.com/jonesrussell/mp-emailer/logger"
	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

type MockInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInterface) EXPECT() *MockInterface_Expecter {
	return &MockInterface_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: msg, fields
func (_m *MockInterface) Debug(msg string, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// MockInterface_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type MockInterface_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - msg string
//   - fields ...interface{}
func (_e *MockInterface_Expecter) Debug(msg interface{}, fields ...interface{}) *MockInterface_Debug_Call {
	return &MockInterface_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockInterface_Debug_Call) Run(run func(msg string, fields ...interface{})) *MockInterface_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Debug_Call) Return() *MockInterface_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Debug_Call) RunAndReturn(run func(string, ...interface{})) *MockInterface_Debug_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function with given fields: msg, err, fields
func (_m *MockInterface) Error(msg string, err error, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg, err)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// MockInterface_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockInterface_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - err error
//   - fields ...interface{}
func (_e *MockInterface_Expecter) Error(msg interface{}, err interface{}, fields ...interface{}) *MockInterface_Error_Call {
	return &MockInterface_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{msg, err}, fields...)...)}
}

func (_c *MockInterface_Error_Call) Run(run func(msg string, err error, fields ...interface{})) *MockInterface_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Error_Call) Return() *MockInterface_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Error_Call) RunAndReturn(run func(string, error, ...interface{})) *MockInterface_Error_Call {
	_c.Call.Return(run)
	return _c
}

// Fatal provides a mock function with given fields: msg, err, fields
func (_m *MockInterface) Fatal(msg string, err error, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg, err)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// MockInterface_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type MockInterface_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - msg string
//   - err error
//   - fields ...interface{}
func (_e *MockInterface_Expecter) Fatal(msg interface{}, err interface{}, fields ...interface{}) *MockInterface_Fatal_Call {
	return &MockInterface_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{msg, err}, fields...)...)}
}

func (_c *MockInterface_Fatal_Call) Run(run func(msg string, err error, fields ...interface{})) *MockInterface_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), args[1].(error), variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Fatal_Call) Return() *MockInterface_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Fatal_Call) RunAndReturn(run func(string, error, ...interface{})) *MockInterface_Fatal_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function with given fields: msg, fields
func (_m *MockInterface) Info(msg string, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// MockInterface_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockInterface_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - fields ...interface{}
func (_e *MockInterface_Expecter) Info(msg interface{}, fields ...interface{}) *MockInterface_Info_Call {
	return &MockInterface_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockInterface_Info_Call) Run(run func(msg string, fields ...interface{})) *MockInterface_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Info_Call) Return() *MockInterface_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Info_Call) RunAndReturn(run func(string, ...interface{})) *MockInterface_Info_Call {
	_c.Call.Return(run)
	return _c
}

// IsDebugEnabled provides a mock function with given fields:
func (_m *MockInterface) IsDebugEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDebugEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockInterface_IsDebugEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDebugEnabled'
type MockInterface_IsDebugEnabled_Call struct {
	*mock.Call
}

// IsDebugEnabled is a helper method to define mock.On call
func (_e *MockInterface_Expecter) IsDebugEnabled() *MockInterface_IsDebugEnabled_Call {
	return &MockInterface_IsDebugEnabled_Call{Call: _e.mock.On("IsDebugEnabled")}
}

func (_c *MockInterface_IsDebugEnabled_Call) Run(run func()) *MockInterface_IsDebugEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInterface_IsDebugEnabled_Call) Return(_a0 bool) *MockInterface_IsDebugEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterface_IsDebugEnabled_Call) RunAndReturn(run func() bool) *MockInterface_IsDebugEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// Warn provides a mock function with given fields: msg, fields
func (_m *MockInterface) Warn(msg string, fields ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	_ca = append(_ca, fields...)
	_m.Called(_ca...)
}

// MockInterface_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type MockInterface_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - msg string
//   - fields ...interface{}
func (_e *MockInterface_Expecter) Warn(msg interface{}, fields ...interface{}) *MockInterface_Warn_Call {
	return &MockInterface_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{msg}, fields...)...)}
}

func (_c *MockInterface_Warn_Call) Run(run func(msg string, fields ...interface{})) *MockInterface_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_Warn_Call) Return() *MockInterface_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockInterface_Warn_Call) RunAndReturn(run func(string, ...interface{})) *MockInterface_Warn_Call {
	_c.Call.Return(run)
	return _c
}

// With provides a mock function with given fields: fields
func (_m *MockInterface) With(fields ...interface{}) logger.Interface {
	var _ca []interface{}
	_ca = append(_ca, fields...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 logger.Interface
	if rf, ok := ret.Get(0).(func(...interface{}) logger.Interface); ok {
		r0 = rf(fields...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Interface)
		}
	}

	return r0
}

// MockInterface_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type MockInterface_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - fields ...interface{}
func (_e *MockInterface_Expecter) With(fields ...interface{}) *MockInterface_With_Call {
	return &MockInterface_With_Call{Call: _e.mock.On("With",
		append([]interface{}{}, fields...)...)}
}

func (_c *MockInterface_With_Call) Run(run func(fields ...interface{})) *MockInterface_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockInterface_With_Call) Return(_a0 logger.Interface) *MockInterface_With_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterface_With_Call) RunAndReturn(run func(...interface{}) logger.Interface) *MockInterface_With_Call {
	_c.Call.Return(run)
	return _c
}

// WithOperation provides a mock function with given fields: operation
func (_m *MockInterface) WithOperation(operation string) logger.Interface {
	ret := _m.Called(operation)

	if len(ret) == 0 {
		panic("no return value specified for WithOperation")
	}

	var r0 logger.Interface
	if rf, ok := ret.Get(0).(func(string) logger.Interface); ok {
		r0 = rf(operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logger.Interface)
		}
	}

	return r0
}

// MockInterface_WithOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithOperation'
type MockInterface_WithOperation_Call struct {
	*mock.Call
}

// WithOperation is a helper method to define mock.On call
//   - operation string
func (_e *MockInterface_Expecter) WithOperation(operation interface{}) *MockInterface_WithOperation_Call {
	return &MockInterface_WithOperation_Call{Call: _e.mock.On("WithOperation", operation)}
}

func (_c *MockInterface_WithOperation_Call) Run(run func(operation string)) *MockInterface_WithOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockInterface_WithOperation_Call) Return(_a0 logger.Interface) *MockInterface_WithOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInterface_WithOperation_Call) RunAndReturn(run func(string) logger.Interface) *MockInterface_WithOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInterface creates a new instance of MockInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInterface {
	mock := &MockInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
